-- (c) Copyright 1995-2022 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
-- DO NOT MODIFY THIS FILE.

-- IP VLNV: xilinx.com:ip:dfx_decoupler:1.0
-- IP Revision: 2

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY design_1_dfx_decoupler_0_0 IS
  PORT (
    s_CNTMOD_B2R_ARVALID : IN STD_LOGIC;
    rp_CNTMOD_B2R_ARVALID : OUT STD_LOGIC;
    s_CNTMOD_B2R_ARREADY : OUT STD_LOGIC;
    rp_CNTMOD_B2R_ARREADY : IN STD_LOGIC;
    s_CNTMOD_B2R_AWVALID : IN STD_LOGIC;
    rp_CNTMOD_B2R_AWVALID : OUT STD_LOGIC;
    s_CNTMOD_B2R_AWREADY : OUT STD_LOGIC;
    rp_CNTMOD_B2R_AWREADY : IN STD_LOGIC;
    s_CNTMOD_B2R_BVALID : OUT STD_LOGIC;
    rp_CNTMOD_B2R_BVALID : IN STD_LOGIC;
    s_CNTMOD_B2R_BREADY : IN STD_LOGIC;
    rp_CNTMOD_B2R_BREADY : OUT STD_LOGIC;
    s_CNTMOD_B2R_RVALID : OUT STD_LOGIC;
    rp_CNTMOD_B2R_RVALID : IN STD_LOGIC;
    s_CNTMOD_B2R_RREADY : IN STD_LOGIC;
    rp_CNTMOD_B2R_RREADY : OUT STD_LOGIC;
    s_CNTMOD_B2R_WVALID : IN STD_LOGIC;
    rp_CNTMOD_B2R_WVALID : OUT STD_LOGIC;
    s_CNTMOD_B2R_WREADY : OUT STD_LOGIC;
    rp_CNTMOD_B2R_WREADY : IN STD_LOGIC;
    s_CNTMOD_B2R_AWADDR : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    rp_CNTMOD_B2R_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_CNTMOD_B2R_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    rp_CNTMOD_B2R_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    s_CNTMOD_B2R_AWREGION : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    rp_CNTMOD_B2R_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_CNTMOD_B2R_AWQOS : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    rp_CNTMOD_B2R_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_CNTMOD_B2R_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    rp_CNTMOD_B2R_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_CNTMOD_B2R_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    rp_CNTMOD_B2R_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_CNTMOD_B2R_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    rp_CNTMOD_B2R_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    s_CNTMOD_B2R_ARADDR : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    rp_CNTMOD_B2R_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_CNTMOD_B2R_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
    rp_CNTMOD_B2R_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    s_CNTMOD_B2R_ARREGION : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    rp_CNTMOD_B2R_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_CNTMOD_B2R_ARQOS : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    rp_CNTMOD_B2R_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_CNTMOD_B2R_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    rp_CNTMOD_B2R_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_CNTMOD_B2R_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    rp_CNTMOD_B2R_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    decouple : IN STD_LOGIC;
    decouple_status : OUT STD_LOGIC
  );
END design_1_dfx_decoupler_0_0;

ARCHITECTURE design_1_dfx_decoupler_0_0_arch OF design_1_dfx_decoupler_0_0 IS
  ATTRIBUTE DowngradeIPIdentifiedWarnings : STRING;
  ATTRIBUTE DowngradeIPIdentifiedWarnings OF design_1_dfx_decoupler_0_0_arch: ARCHITECTURE IS "yes";
  COMPONENT dfx_decoupler_design_1_dfx_decoupler_0_0 IS
    GENERIC (
      C_XDEVICEFAMILY : STRING
    );
    PORT (
      s_CNTMOD_B2R_ARVALID : IN STD_LOGIC;
      rp_CNTMOD_B2R_ARVALID : OUT STD_LOGIC;
      s_CNTMOD_B2R_ARREADY : OUT STD_LOGIC;
      rp_CNTMOD_B2R_ARREADY : IN STD_LOGIC;
      s_CNTMOD_B2R_AWVALID : IN STD_LOGIC;
      rp_CNTMOD_B2R_AWVALID : OUT STD_LOGIC;
      s_CNTMOD_B2R_AWREADY : OUT STD_LOGIC;
      rp_CNTMOD_B2R_AWREADY : IN STD_LOGIC;
      s_CNTMOD_B2R_BVALID : OUT STD_LOGIC;
      rp_CNTMOD_B2R_BVALID : IN STD_LOGIC;
      s_CNTMOD_B2R_BREADY : IN STD_LOGIC;
      rp_CNTMOD_B2R_BREADY : OUT STD_LOGIC;
      s_CNTMOD_B2R_RVALID : OUT STD_LOGIC;
      rp_CNTMOD_B2R_RVALID : IN STD_LOGIC;
      s_CNTMOD_B2R_RREADY : IN STD_LOGIC;
      rp_CNTMOD_B2R_RREADY : OUT STD_LOGIC;
      s_CNTMOD_B2R_WVALID : IN STD_LOGIC;
      rp_CNTMOD_B2R_WVALID : OUT STD_LOGIC;
      s_CNTMOD_B2R_WREADY : OUT STD_LOGIC;
      rp_CNTMOD_B2R_WREADY : IN STD_LOGIC;
      s_CNTMOD_B2R_AWADDR : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      rp_CNTMOD_B2R_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_CNTMOD_B2R_AWPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      rp_CNTMOD_B2R_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      s_CNTMOD_B2R_AWREGION : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      rp_CNTMOD_B2R_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_CNTMOD_B2R_AWQOS : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      rp_CNTMOD_B2R_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_CNTMOD_B2R_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      rp_CNTMOD_B2R_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_CNTMOD_B2R_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      rp_CNTMOD_B2R_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_CNTMOD_B2R_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      rp_CNTMOD_B2R_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      s_CNTMOD_B2R_ARADDR : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      rp_CNTMOD_B2R_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_CNTMOD_B2R_ARPROT : IN STD_LOGIC_VECTOR(2 DOWNTO 0);
      rp_CNTMOD_B2R_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      s_CNTMOD_B2R_ARREGION : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      rp_CNTMOD_B2R_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_CNTMOD_B2R_ARQOS : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      rp_CNTMOD_B2R_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_CNTMOD_B2R_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      rp_CNTMOD_B2R_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_CNTMOD_B2R_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      rp_CNTMOD_B2R_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      decouple : IN STD_LOGIC;
      decouple_status : OUT STD_LOGIC
    );
  END COMPONENT dfx_decoupler_design_1_dfx_decoupler_0_0;
  ATTRIBUTE X_CORE_INFO : STRING;
  ATTRIBUTE X_CORE_INFO OF design_1_dfx_decoupler_0_0_arch: ARCHITECTURE IS "dfx_decoupler_design_1_dfx_decoupler_0_0,Vivado 2021.1";
  ATTRIBUTE CHECK_LICENSE_TYPE : STRING;
  ATTRIBUTE CHECK_LICENSE_TYPE OF design_1_dfx_decoupler_0_0_arch : ARCHITECTURE IS "design_1_dfx_decoupler_0_0,dfx_decoupler_design_1_dfx_decoupler_0_0,{}";
  ATTRIBUTE CORE_GENERATION_INFO : STRING;
  ATTRIBUTE CORE_GENERATION_INFO OF design_1_dfx_decoupler_0_0_arch: ARCHITECTURE IS "design_1_dfx_decoupler_0_0,dfx_decoupler_design_1_dfx_decoupler_0_0,{x_ipProduct=Vivado 2021.1,x_ipVendor=xilinx.com,x_ipLibrary=ip,x_ipName=dfx_decoupler,x_ipVersion=1.0,x_ipCoreRevision=2,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_XDEVICEFAMILY=zynq}";
  ATTRIBUTE X_INTERFACE_INFO : STRING;
  ATTRIBUTE X_INTERFACE_PARAMETER : STRING;
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R ARREADY";
  ATTRIBUTE X_INTERFACE_PARAMETER OF rp_CNTMOD_B2R_ARVALID: SIGNAL IS "XIL_INTERFACENAME rp_CNTMOD_B2R, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 50000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, " & 
"WUSER_BITS_PER_BYTE 0, INSERT_VIP 0, MISC.CLK_REQUIRED FALSE";
  ATTRIBUTE X_INTERFACE_INFO OF rp_CNTMOD_B2R_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 rp_CNTMOD_B2R ARVALID";
  ATTRIBUTE X_INTERFACE_PARAMETER OF s_CNTMOD_B2R_ARVALID: SIGNAL IS "XIL_INTERFACENAME s_CNTMOD_B2R, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 50000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, W" & 
"USER_BITS_PER_BYTE 0, INSERT_VIP 0, MISC.CLK_REQUIRED FALSE";
  ATTRIBUTE X_INTERFACE_INFO OF s_CNTMOD_B2R_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_CNTMOD_B2R ARVALID";
BEGIN
  U0 : dfx_decoupler_design_1_dfx_decoupler_0_0
    GENERIC MAP (
      C_XDEVICEFAMILY => "zynq"
    )
    PORT MAP (
      s_CNTMOD_B2R_ARVALID => s_CNTMOD_B2R_ARVALID,
      rp_CNTMOD_B2R_ARVALID => rp_CNTMOD_B2R_ARVALID,
      s_CNTMOD_B2R_ARREADY => s_CNTMOD_B2R_ARREADY,
      rp_CNTMOD_B2R_ARREADY => rp_CNTMOD_B2R_ARREADY,
      s_CNTMOD_B2R_AWVALID => s_CNTMOD_B2R_AWVALID,
      rp_CNTMOD_B2R_AWVALID => rp_CNTMOD_B2R_AWVALID,
      s_CNTMOD_B2R_AWREADY => s_CNTMOD_B2R_AWREADY,
      rp_CNTMOD_B2R_AWREADY => rp_CNTMOD_B2R_AWREADY,
      s_CNTMOD_B2R_BVALID => s_CNTMOD_B2R_BVALID,
      rp_CNTMOD_B2R_BVALID => rp_CNTMOD_B2R_BVALID,
      s_CNTMOD_B2R_BREADY => s_CNTMOD_B2R_BREADY,
      rp_CNTMOD_B2R_BREADY => rp_CNTMOD_B2R_BREADY,
      s_CNTMOD_B2R_RVALID => s_CNTMOD_B2R_RVALID,
      rp_CNTMOD_B2R_RVALID => rp_CNTMOD_B2R_RVALID,
      s_CNTMOD_B2R_RREADY => s_CNTMOD_B2R_RREADY,
      rp_CNTMOD_B2R_RREADY => rp_CNTMOD_B2R_RREADY,
      s_CNTMOD_B2R_WVALID => s_CNTMOD_B2R_WVALID,
      rp_CNTMOD_B2R_WVALID => rp_CNTMOD_B2R_WVALID,
      s_CNTMOD_B2R_WREADY => s_CNTMOD_B2R_WREADY,
      rp_CNTMOD_B2R_WREADY => rp_CNTMOD_B2R_WREADY,
      s_CNTMOD_B2R_AWADDR => s_CNTMOD_B2R_AWADDR,
      rp_CNTMOD_B2R_AWADDR => rp_CNTMOD_B2R_AWADDR,
      s_CNTMOD_B2R_AWPROT => s_CNTMOD_B2R_AWPROT,
      rp_CNTMOD_B2R_AWPROT => rp_CNTMOD_B2R_AWPROT,
      s_CNTMOD_B2R_AWREGION => s_CNTMOD_B2R_AWREGION,
      rp_CNTMOD_B2R_AWREGION => rp_CNTMOD_B2R_AWREGION,
      s_CNTMOD_B2R_AWQOS => s_CNTMOD_B2R_AWQOS,
      rp_CNTMOD_B2R_AWQOS => rp_CNTMOD_B2R_AWQOS,
      s_CNTMOD_B2R_WDATA => s_CNTMOD_B2R_WDATA,
      rp_CNTMOD_B2R_WDATA => rp_CNTMOD_B2R_WDATA,
      s_CNTMOD_B2R_WSTRB => s_CNTMOD_B2R_WSTRB,
      rp_CNTMOD_B2R_WSTRB => rp_CNTMOD_B2R_WSTRB,
      s_CNTMOD_B2R_BRESP => s_CNTMOD_B2R_BRESP,
      rp_CNTMOD_B2R_BRESP => rp_CNTMOD_B2R_BRESP,
      s_CNTMOD_B2R_ARADDR => s_CNTMOD_B2R_ARADDR,
      rp_CNTMOD_B2R_ARADDR => rp_CNTMOD_B2R_ARADDR,
      s_CNTMOD_B2R_ARPROT => s_CNTMOD_B2R_ARPROT,
      rp_CNTMOD_B2R_ARPROT => rp_CNTMOD_B2R_ARPROT,
      s_CNTMOD_B2R_ARREGION => s_CNTMOD_B2R_ARREGION,
      rp_CNTMOD_B2R_ARREGION => rp_CNTMOD_B2R_ARREGION,
      s_CNTMOD_B2R_ARQOS => s_CNTMOD_B2R_ARQOS,
      rp_CNTMOD_B2R_ARQOS => rp_CNTMOD_B2R_ARQOS,
      s_CNTMOD_B2R_RDATA => s_CNTMOD_B2R_RDATA,
      rp_CNTMOD_B2R_RDATA => rp_CNTMOD_B2R_RDATA,
      s_CNTMOD_B2R_RRESP => s_CNTMOD_B2R_RRESP,
      rp_CNTMOD_B2R_RRESP => rp_CNTMOD_B2R_RRESP,
      decouple => decouple,
      decouple_status => decouple_status
    );
END design_1_dfx_decoupler_0_0_arch;
