
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_AXI_INTC_1_DEVICE_ID,
		XPAR_AXI_INTC_1_BASEADDR,
		XPAR_AXI_INTC_1_KIND_OF_INTR,
		XPAR_AXI_INTC_1_HAS_FAST,
		XPAR_AXI_INTC_1_IVAR_RESET_VALUE,
		XPAR_AXI_INTC_1_NUM_INTR_INPUTS,
		XPAR_AXI_INTC_1_ADDR_WIDTH,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_AXI_INTC_1_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			}
		},
		XPAR_AXI_INTC_1_NUM_SW_INTR
	}
};

