set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_0_tri_o[0]}]
set_property PACKAGE_PIN R14 [get_ports {gpio_rtl_0_tri_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {vsm_VS_0_hw_triggers[0]}]
set_property PACKAGE_PIN D19 [get_ports {vsm_VS_0_hw_triggers[0]}]

create_pblock pblock_mcrblz_0_instnc
resize_pblock [get_pblocks pblock_mcrblz_0_instnc] -add {SLICE_X50Y101:SLICE_X67Y149}
resize_pblock [get_pblocks pblock_mcrblz_0_instnc] -add {RAMB18_X3Y42:RAMB18_X3Y59}
resize_pblock [get_pblocks pblock_mcrblz_0_instnc] -add {RAMB36_X3Y21:RAMB36_X3Y29}
add_cells_to_pblock [get_pblocks pblock_mcrblz_0_instnc] [get_cells -quiet [list microblaze_0_instance]]



create_pblock pblock_mcrblz_0_instnc_1
resize_pblock [get_pblocks pblock_mcrblz_0_instnc_1] -add {SLICE_X54Y19:SLICE_X89Y48}

set_property PROHIBIT true [get_sites SLICE_X54Y48]
set_property PROHIBIT true [get_sites SLICE_X55Y48]
set_property PROHIBIT true [get_sites SLICE_X54Y47]
set_property PROHIBIT true [get_sites SLICE_X55Y47]
set_property PROHIBIT true [get_sites SLICE_X54Y46]
set_property PROHIBIT true [get_sites SLICE_X55Y46]
set_property PROHIBIT true [get_sites RAMB36_X3Y9]
set_property PROHIBIT true [get_sites RAMB18_X3Y18]
set_property PROHIBIT true [get_sites RAMB18_X3Y19]
set_property PROHIBIT true [get_sites SLICE_X54Y45]
set_property PROHIBIT true [get_sites SLICE_X55Y45]
set_property PROHIBIT true [get_sites SLICE_X54Y44]
set_property PROHIBIT true [get_sites SLICE_X55Y44]
set_property PROHIBIT true [get_sites SLICE_X54Y43]
set_property PROHIBIT true [get_sites SLICE_X55Y43]
set_property PROHIBIT true [get_sites SLICE_X54Y42]
set_property PROHIBIT true [get_sites SLICE_X55Y42]
set_property PROHIBIT true [get_sites SLICE_X54Y41]
set_property PROHIBIT true [get_sites SLICE_X55Y41]
set_property PROHIBIT true [get_sites RAMB36_X3Y8]
set_property PROHIBIT true [get_sites RAMB18_X3Y16]
set_property PROHIBIT true [get_sites RAMB18_X3Y17]
set_property PROHIBIT true [get_sites SLICE_X54Y40]
set_property PROHIBIT true [get_sites SLICE_X55Y40]
set_property PROHIBIT true [get_sites SLICE_X54Y39]
set_property PROHIBIT true [get_sites SLICE_X55Y39]
set_property PROHIBIT true [get_sites SLICE_X54Y38]
set_property PROHIBIT true [get_sites SLICE_X55Y38]
set_property PROHIBIT true [get_sites SLICE_X54Y37]
set_property PROHIBIT true [get_sites SLICE_X55Y37]
set_property PROHIBIT true [get_sites SLICE_X54Y36]
set_property PROHIBIT true [get_sites SLICE_X55Y36]
set_property PROHIBIT true [get_sites RAMB36_X3Y7]
set_property PROHIBIT true [get_sites RAMB18_X3Y14]
set_property PROHIBIT true [get_sites RAMB18_X3Y15]
set_property PROHIBIT true [get_sites SLICE_X54Y35]
set_property PROHIBIT true [get_sites SLICE_X55Y35]
set_property PROHIBIT true [get_sites SLICE_X54Y34]
set_property PROHIBIT true [get_sites SLICE_X55Y34]
set_property PROHIBIT true [get_sites SLICE_X54Y33]
set_property PROHIBIT true [get_sites SLICE_X55Y33]
set_property PROHIBIT true [get_sites SLICE_X54Y32]
set_property PROHIBIT true [get_sites SLICE_X55Y32]
set_property PROHIBIT true [get_sites SLICE_X54Y31]
set_property PROHIBIT true [get_sites SLICE_X55Y31]
set_property PROHIBIT true [get_sites RAMB36_X3Y6]
set_property PROHIBIT true [get_sites RAMB18_X3Y12]
set_property PROHIBIT true [get_sites RAMB18_X3Y13]
set_property PROHIBIT true [get_sites SLICE_X54Y30]
set_property PROHIBIT true [get_sites SLICE_X55Y30]
set_property PROHIBIT true [get_sites SLICE_X54Y29]
set_property PROHIBIT true [get_sites SLICE_X55Y29]
set_property PROHIBIT true [get_sites SLICE_X54Y28]
set_property PROHIBIT true [get_sites SLICE_X55Y28]
set_property PROHIBIT true [get_sites SLICE_X54Y27]
set_property PROHIBIT true [get_sites SLICE_X55Y27]
set_property PROHIBIT true [get_sites SLICE_X54Y26]
set_property PROHIBIT true [get_sites SLICE_X55Y26]
set_property PROHIBIT true [get_sites RAMB36_X3Y5]
set_property PROHIBIT true [get_sites RAMB18_X3Y10]
set_property PROHIBIT true [get_sites RAMB18_X3Y11]
set_property PROHIBIT true [get_sites SLICE_X54Y25]
set_property PROHIBIT true [get_sites SLICE_X55Y25]
set_property PROHIBIT true [get_sites SLICE_X54Y24]
set_property PROHIBIT true [get_sites SLICE_X55Y24]
set_property PROHIBIT true [get_sites SLICE_X54Y23]
set_property PROHIBIT true [get_sites SLICE_X55Y23]
set_property PROHIBIT true [get_sites SLICE_X54Y22]
set_property PROHIBIT true [get_sites SLICE_X55Y22]
set_property PROHIBIT true [get_sites SLICE_X54Y21]
set_property PROHIBIT true [get_sites SLICE_X55Y21]
set_property PROHIBIT true [get_sites RAMB36_X3Y4]
set_property PROHIBIT true [get_sites RAMB18_X3Y8]
set_property PROHIBIT true [get_sites RAMB18_X3Y9]
set_property PROHIBIT true [get_sites SLICE_X54Y20]
set_property PROHIBIT true [get_sites SLICE_X55Y20]
set_property PROHIBIT true [get_sites SLICE_X54Y19]
set_property PROHIBIT true [get_sites SLICE_X55Y19]
set_property PROHIBIT true [get_sites RAMB36_X3Y3]
set_property PROHIBIT true [get_sites RAMB18_X3Y6]
set_property PROHIBIT true [get_sites RAMB18_X3Y7]
set_property PROHIBIT true [get_sites RAMB36_X3Y2]
set_property PROHIBIT true [get_sites RAMB18_X3Y4]
set_property PROHIBIT true [get_sites RAMB18_X3Y5]
set_property PROHIBIT true [get_sites RAMB36_X3Y1]
set_property PROHIBIT true [get_sites RAMB18_X3Y2]
set_property PROHIBIT true [get_sites RAMB18_X3Y3]
set_property PROHIBIT true [get_sites RAMB36_X3Y0]
set_property PROHIBIT true [get_sites RAMB18_X3Y0]
set_property PROHIBIT true [get_sites RAMB18_X3Y1]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets microblaze_0_Clk]

set_property PACKAGE_PIN V6 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN Y6 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]

set_property PACKAGE_PIN M20 [get_ports inhibit_rec]
set_property IOSTANDARD LVCMOS33 [get_ports inhibit_rec]

set_property PACKAGE_PIN G17 [get_ports inhib_status]
set_property IOSTANDARD LVCMOS33 [get_ports inhib_status]